In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score, confusion_matrix

In [2]:
df = pd.read_csv("./loan_approval.csv")

## 1. Understanding the Dataset

In [3]:
df.shape

(4000, 11)

In [4]:
df.columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'CreditHistory', 'Dependents', 'Education',
       'EmploymentType', 'PropertyArea', 'MaritalStatus', 'Loan_Status'],
      dtype='str')

In [5]:
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,CreditHistory,Dependents,Education,EmploymentType,PropertyArea,MaritalStatus,Loan_Status
0,136958,50772,298430,300,1,2,Not Graduate,Self Employed,Semiurban,Single,1
1,146932,72084,205887,120,0,1,Graduate,Salaried,Semiurban,Married,1
2,118694,40149,265572,180,1,3+,Graduate,Self Employed,Rural,Single,1
3,134879,27526,144348,36,1,0,Not Graduate,Self Employed,Urban,Single,1
4,125268,68477,155736,240,1,3+,Not Graduate,Self Employed,Urban,Single,1

In [6]:
df.isnull().sum()

ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
CreditHistory        0
Dependents           0
Education            0
EmploymentType       0
PropertyArea         0
MaritalStatus        0
Loan_Status          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantIncome    4000 non-null   int64
 1   CoapplicantIncome  4000 non-null   int64
 2   LoanAmount         4000 non-null   int64
 3   Loan_Amount_Term   4000 non-null   int64
 4   CreditHistory      4000 non-null   int64
 5   Dependents         4000 non-null   str
 6   Education          4000 non-null   str
 7   EmploymentType     4000 non-null   str
 8   PropertyArea       4000 non-null   str
 9   MaritalStatus      4000 non-null   str
 10  Loan_Status        4000 non-null   int64
dtypes: int64(6), str(5)
memory usage: 343.9 KB

In [9]:
df["Loan_Status"].value_counts()

Loan_Status
1    3347
0     653
Name: count, dtype: int64

In [10]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,CreditHistory,Loan_Status
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000
mean,82404.366000,39191.448500,274527.928500,130.887000,0.754500,0.83675
std,39198.475219,23315.772335,128765.760647,96.149656,0.430437,0.36964
min,15126.000000,2.000000,50015.000000,12.000000,0.000000,0.00000
25%,48217.750000,19071.000000,163228.000000,60.000000,1.000000,1.00000
50%,82401.000000,38617.000000,276918.000000,120.000000,1.000000,1.00000
75%,116021.750000,59256.750000,384040.750000,240.000000,1.000000,1.00000
max,149869.000000,79980.000000,499998.000000,300.000000,1.000000,1.00000